export enum ActionTypes {
  SIGN_IN_START = "SIGN_IN_START",
  SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE = "SIGN_IN_FAILURE",
  SIGN_OUT = "SIGN_OUT",
  SET_ADDED_CARD = "SET_ADDED_CARD",
}
