export enum ActionTypes {
  ADD_CARD_START = "ADD_CARD_START",
  ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS",
  ADD_CARD_FAILURE = "ADD_CARD_FAILURE",
  GET_CARDS_START = "GET_CARDS_START",
  GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS",
  GET_CARDS_FAILURE = "GET_CARDS_FAILURE",
  UPDATE_CARD_START = "UPDATE_CARD_START",
  UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS",
  UPDATE_CARD_FAILURE = "UPDATE_CARD_FAILURE",
}
